# Generated by Django 5.2.3 on 2025-09-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='school_banners/')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_historical_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_images', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='AlumniHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='school_alumni_images/')),
                ('name', models.CharField(max_length=255)),
                ('quote', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_highlights', to='schools.school')),
            ],
        ),
    ]
