# Generated by Django 5.2.6 on 2025-09-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='school_banners/'),
        ),
        migrations.CreateModel(
            name='SchoolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('historical', 'Historical'), ('alumni', 'Alumni')], default='alumni', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='schools.school')),
            ],
        ),
    ]
