# Generated by Django 5.2.6 on 2025-09-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_banner_schoolphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='banner',
        ),
        migrations.DeleteModel(
            name='SchoolPhoto',
        ),
    ]
