# Generated by Django 5.2.6 on 2025-09-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_banner_delete_schoolphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_banners/'),
        ),
        migrations.CreateModel(
            name='AlumniHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='school_alumni_images/')),
                ('name', models.CharField(max_length=255)),
                ('quote', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_highlights', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_historical_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_images', to='schools.school')),
            ],
        ),
    ]
