# Generated by Django 5.2.3 on 2025-09-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='births_deaths_and_marriages',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdm_updates', to='schools.school'),
        ),
    ]
