# Generated by Django 5.2.3 on 2025-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_births_deaths_and_marriages_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='births_deaths_and_marriages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media/news/articles', verbose_name=''),
        ),
    ]
