# Generated by Django 5.2.3 on 2025-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_births_deaths_and_marriages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='births_deaths_and_marriages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/articles'),
        ),
    ]
